{{- if not .Values.hackthe6ixDiscord.secrets.vault.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hackthe6ix-discord.fullname" . }}-secrets
data:
  DISCORD_BOT_TOKEN: {{ .Values.hackthe6ixDiscord.secrets.local.discordBotToken | b64enc }}
  DISCORD_ROLES_MAP: {{ .Values.hackthe6ixDiscord.secrets.local.discordRolesMap | b64enc }}
  ADMIN_ROLE_IDS: {{ .Values.hackthe6ixDiscord.secrets.local.discordAdminRoleIds | b64enc }}
  VERIFIED_ROLE_ID: {{ .Values.hackthe6ixDiscord.secrets.local.discordVerifiedRoleId | b64enc }}
  VERIFICATION_CHANNEL_ID: {{ .Values.hackthe6ixDiscord.secrets.local.discordVerificationChannelId | b64enc }}
  API_TOKEN: {{ .Values.hackthe6ixDiscord.secrets.local.apiToken | b64enc }}
  {{- end }}